- hosts: webserver
  gather_facts: yes
  become: yes
  become_user: root
  tags: always
  tasks:
    - include_role:
        name: common
    - include_role:
        name: db
    - include_role:
        name: web